### ISSUE TITLE
Pre-trained generators for GreedyFool

### ISSUE THREAD

**Issue by toobaimt** [shaguopohuaizhe/TSAA#1]
Hi,
In your paper, you perform transferability experiments on GreedyFool trained on ResNet50 and evaluate on other classifiers. Are you using the same pre-trained Inceptionv3 generator provided by the authors for ResNet50 as well? Or did you train another one from scratch?
Thanks

**Comment by shaguopohuaizhe** [comment]
Hi,
We use pre-trained ImageNet models provided in TorchVision.

**Comment by toobaimt** [comment]
Thanks for responding.
I believe that's for the targetted model. I'm talking about the generator (see [this](https://github.com/LightDXY/GreedyFool/blob/main/nips_gd.py#:~:text=netG%20%3D%20generators.Res_ResnetGenerator(3%2C%201%2C%2016%2C%20norm_type%3D%27batch%27%2C%20act_type%3D%27relu%27))). Are you evaluating with the same pretrained weights for all architectures (ResNet50, etc.)?

**Comment by shaguopohuaizhe** [comment]
Regarding GreedyFool, we follow [nips_black_gd.py](https://github.com/LightDXY/GreedyFool/blob/main/nips_black_gd.py) for evaluation and it does not include the distortion map generator in [nips_gd.py](https://github.com/LightDXY/GreedyFool/blob/main/nips_gd.py).

**Comment by toobaimt** [comment]
Got it, thank you!
